/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsNewIndexRouteImport } from './routes/posts/new/index'
import { Route as PostsPostIdIndexRouteImport } from './routes/posts/$postId/index'
import { Route as PostsPostIdEditIndexRouteImport } from './routes/posts/$postId/edit/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsNewIndexRoute = PostsNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PostsPostIdEditIndexRoute = PostsPostIdEditIndexRouteImport.update({
  id: '/$postId/edit/',
  path: '/$postId/edit/',
  getParentRoute: () => PostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/new/': typeof PostsNewIndexRoute
  '/posts/$postId/edit/': typeof PostsPostIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
  '/posts/new': typeof PostsNewIndexRoute
  '/posts/$postId/edit': typeof PostsPostIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts': typeof PostsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
  '/posts/new/': typeof PostsNewIndexRoute
  '/posts/$postId/edit/': typeof PostsPostIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/about'
    | '/posts/'
    | '/posts/$postId/'
    | '/posts/new/'
    | '/posts/$postId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/posts'
    | '/posts/$postId'
    | '/posts/new'
    | '/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/posts'
    | '/about'
    | '/posts/'
    | '/posts/$postId/'
    | '/posts/new/'
    | '/posts/$postId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/new/': {
      id: '/posts/new/'
      path: '/new'
      fullPath: '/posts/new/'
      preLoaderRoute: typeof PostsNewIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/$postId'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId/edit/': {
      id: '/posts/$postId/edit/'
      path: '/$postId/edit'
      fullPath: '/posts/$postId/edit/'
      preLoaderRoute: typeof PostsPostIdEditIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
  PostsNewIndexRoute: typeof PostsNewIndexRoute
  PostsPostIdEditIndexRoute: typeof PostsPostIdEditIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
  PostsNewIndexRoute: PostsNewIndexRoute,
  PostsPostIdEditIndexRoute: PostsPostIdEditIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
